apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq
  namespace: vpro-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprormq
  template:
    metadata:
      labels:
        app: vprormq
    spec:
      containers:
      - name: vprormq
        image: rabbitmq:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: vprormq-port
            containerPort: 15672
        env: 
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: vpro-cret
                key: rmq-pass
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              configMapKeyRef:
                name: vpro-cm
                key: rmq_user
---
apiVersion: v1
kind: Service
metadata:
  name: vpromq01
  namespace: vpro-ns
spec:
  type: ClusterIP
  selector:
    app: vprormq
  ports:
  - port: 15672
    targetPort: vprormq-port
    protocol: TCP