apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
  namespace: vpro-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromc
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
      - name: vpro-mc
        image: memcached:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: vpromc-port
            containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
  namespace: vpro-ns
spec:
  type: ClusterIP
  selector:
    app: vpromc 
  ports:
  - port: 11211
    targetPort: vpromc-port
    protocol: TCP
